/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.slambyte.util.xml;

public class App {
	public static void main(String[] args) {
		String input = args.length > 0 ? args[0]:null;
		String output = args.length == 2 ? args[1]:null;

		new Parser().parseFile(input,output);
		// new Parser().createSvgSkeleton("200","250");
	}
}
